# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-28 15:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Author', models.CharField(max_length=50)),
                ('Subject', models.CharField(max_length=50)),
                ('Rating', models.CharField(max_length=50)),
                ('Summary', models.CharField(max_length=500)),
                ('No_of_Copies', models.CharField(max_length=50)),
                ('No_of_Requests', models.CharField(max_length=50)),
            ],
        ),
    ]
