# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-12 12:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_bookissue'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BookName', models.CharField(max_length=50)),
                ('StudentName', models.CharField(max_length=50)),
                ('Status', models.CharField(choices=[('booked', 'BOOKED'), ('pickedUp', 'PICKED_UP'), ('returned', 'RETURNED')], default='returned', max_length=50)),
                ('IssueDate', models.DateField(null=True)),
            ],
        ),
    ]
