# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-12 13:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_studenthistory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studenthistory',
            old_name='Status',
            new_name='BookStatus',
        ),
    ]
