# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-23 11:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20180712_1303'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookissue',
            name='DaysLeft',
            field=models.IntegerField(default=0),
        ),
    ]
