# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-24 13:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_bookissue_daysleft'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookissue',
            old_name='ReturnDate',
            new_name='IssueDate',
        ),
    ]
