# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-24 13:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20180724_1320'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StudentHistory',
        ),
        migrations.AlterField(
            model_name='bookissue',
            name='StudentName',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.User'),
        ),
    ]
