# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-25 07:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20180724_1353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookissue',
            name='BookName',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Book'),
        ),
    ]
