# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-25 07:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20180725_0732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookissue',
            name='BookName',
            field=models.CharField(max_length=50),
        ),
    ]
